# Generated by Django 5.2.6 on 2025-09-28 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('da_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ta_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.IntegerField(default=0)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.designation')),
            ],
        ),
    ]
